apiVersion: v1
kind: Service
metadata:
  labels:
    name: smartgrid-wechat-portal-client
  name: smartgrid-wechat-portal-client
  namespace: gridvo
spec:
  selector:
    name: smartgrid-wechat-portal-client
  ports:
     - port: 80
       targetPort: 3001
