apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smartgrid-wechat-portal-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smartgrid-wechat-portal-client
    spec:
      containers:
      - name: smartgrid-wechat-portal-client
        image: 10.0.2.62:5000/gridvo/smartgrid-wechat-portal-client:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: ZK_TRACER_HTTP
          value: "true"
        - name: IS_DEBUG
          value: "true"
             
